# Copyright (C) 2026 Frederik Pasch
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""PipelineCallback — base class for file-generating pipeline steps.

Replaces the old ``Variation`` base class. Each callback is a
deterministic function: given parameters → generates exactly ONE set
of output files. The Hydra sweeper handles combinatorics by varying
callback parameters (seed, path_length, etc.) across jobs.

Example callback in a config file::

    pipeline:
      floorplan:
        _target_: robovast_nav.callbacks.FloorplanVariationCallback
        seed: 1
      path:
        _target_: robovast_nav.callbacks.PathRandomCallback
        path_length: 10.0
        seed: 42

Each callback parameter is sweepable::

    vast run -m pipeline.floorplan.seed=1,2,3 pipeline.path.path_length=5.0,10.0
"""

import logging
from importlib.metadata import entry_points
from pathlib import Path
from typing import Any, Dict, Optional

from .context import PipelineContext

logger = logging.getLogger(__name__)


class PipelineCallback:
    """Base class for pipeline callbacks.

    Subclasses implement :meth:`execute` to generate files and update
    the pipeline context. Each callback produces exactly ONE set of
    output files for a given set of parameters.

    The callback chain runs sequentially inside each Hydra job.
    Dependencies between callbacks (e.g., PathCallback needs
    FloorplanCallback output) are resolved via
    :attr:`PipelineContext.generated_files`.
    """

    def execute(self, ctx: PipelineContext) -> PipelineContext:
        """Generate files and update context.

        Implementations should:
        1. Read inputs from ``ctx.generated_files`` (output of previous callbacks).
        2. Read own parameters from ``self`` attributes (set by Hydra instantiate).
        3. Generate ONE set of output files in ``ctx.output_dir``.
        4. Update ``ctx.generated_files`` with output paths.
        5. Update ``ctx.scenario_params`` with scenario parameter values
           (e.g., ``ctx.scenario_params["map_file"] = "/path/to/map.yaml"``).
        6. Optionally append to ``ctx.config_files`` and ``ctx.transient_files``.

        Args:
            ctx: The pipeline context with accumulated state.

        Returns:
            The updated pipeline context.
        """
        return ctx

    def get_input_files(self) -> list[str]:
        """Return relative file paths required from the source directory.

        These files will be copied into the campaign's ``_config/``
        directory to make the campaign self-contained.

        Returns:
            List of relative file paths (relative to the config directory).
        """
        return []

    def get_campaign_transient_files(self) -> list[tuple[str, str]]:
        """Return campaign-level transient files generated by this callback.

        Must be called after :meth:`execute`.

        Returns:
            List of ``(relative_deploy_path, absolute_source_path)`` tuples.
        """
        return []

    @classmethod
    def collect_config_metadata(
        cls,
        config_entry: dict,
        config_dir: Path,
        campaign_dir: Path,
    ) -> dict:
        """Return additional metadata fields for a configuration entry.

        Called during metadata generation for each configuration that
        used this callback. Override to attach domain-specific metadata
        (e.g., map or mesh information).

        Args:
            config_entry: The configuration dict from metadata.
            config_dir: Path to ``<campaign>/<config-name>/``.
            campaign_dir: Path to ``campaign-<id>/``.

        Returns:
            Dictionary of fields to merge into the configuration's metadata.
        """
        return {}

    @classmethod
    def collect_prov_metadata(
        cls,
        config_entry: dict,
        campaign_namespace: Any,
        config_namespace: Any,
        gen_activity_id: str,
    ) -> Optional[Any]:
        """Return domain-specific PROV-O graph contributions.

        Called during PROV-O generation for each configuration that
        used this callback. Override to contribute domain-specific
        provenance nodes.

        Returns:
            A ProvContribution, or None.
        """
        return None


def load_pipeline_callbacks() -> Dict[str, type]:
    """Load all pipeline callback classes from the ``robovast.pipeline_callbacks`` entry-point group.

    Returns:
        Dictionary mapping callback names to their classes.
    """
    callbacks = {}
    try:
        eps = entry_points(group="robovast.pipeline_callbacks")
        for ep in eps:
            try:
                cls = ep.load()
                if isinstance(cls, type) and issubclass(cls, PipelineCallback):
                    callbacks[ep.name] = cls
                else:
                    logger.warning(
                        "Pipeline callback '%s' is not a PipelineCallback subclass, skipping.",
                        ep.name,
                    )
            except Exception as e:
                logger.warning("Failed to load pipeline callback '%s': %s", ep.name, e)
    except Exception:
        pass
    return callbacks
