# Copyright (C) 2026 Frederik Pasch
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Pipeline context — shared state passed through the callback chain."""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from omegaconf import DictConfig


@dataclass
class PipelineContext:
    """Shared state passed through the callback chain.

    Each callback reads from and writes to this context.
    After the pipeline completes, ``scenario_params`` contains the fully
    resolved scenario parameters (including file paths generated by
    callbacks), and ``generated_files`` contains all generated artifacts.

    Attributes:
        scenario_params: The scenario parameters dict. Callbacks update
            this with generated file paths (e.g., map_file, mesh_file).
        generated_files: Accumulated files from callbacks.
            Keys are logical names (e.g., "map_file"), values are
            absolute paths. Used by downstream callbacks to read
            outputs from previous callbacks.
        config_files: List of (deploy_rel_path, source_abs_path) tuples
            for files that must be copied into the campaign's _config/
            directory. Same semantics as the old ``_config_files``.
        transient_files: List of (deploy_rel_path, source_abs_path) tuples
            for campaign-level transient files (_transient/).
        execution: The full execution section (read-only).
        general: General parameters (read-only).
        scenario_file: Resolved absolute path to the .osc scenario file.
        output_dir: Directory where callbacks write generated artifacts.
        base_path: Config directory root (for resolving relative paths).
        scenario_name: The scenario/config name (used in campaign dir naming).
    """
    scenario_params: dict = field(default_factory=dict)
    generated_files: dict[str, Path] = field(default_factory=dict)
    config_files: list[tuple[str, str]] = field(default_factory=list)
    transient_files: list[tuple[str, str]] = field(default_factory=list)
    execution: Any = field(default_factory=dict)
    general: Any = field(default_factory=dict)
    scenario_file: Path = field(default_factory=Path)
    output_dir: Path = field(default_factory=Path)
    base_path: Path = field(default_factory=Path)
    scenario_name: str = ""
