# Copyright (C) 2026 Frederik Pasch
#
# SPDX-License-Identifier: Apache-2.0

"""Aux-container discovery covers ``execution.generate``, not only variations.

The cluster lane creates the campaign's auxiliary pod, and installs a container-runner factory
at all, only when discovery reports at least one required ``ContainerSpec``. Discovery asked the
variations and nothing else -- so a campaign whose *input generator* declared an ``image:`` got no
pod, no factory, and then failed while composing with

    input generator 'shell' requires the auxiliary container 'aux-family' ...
    No execution-backend container runner is active here

which is doubly misleading: it names validating and previewing as the runner-less contexts, and
this was a campaign. Measured on a real cluster launch of an arm example whose description is
generated by ``roqsim export moveit`` in the simulator image -- the campaign failed at the
variation phase, before a single trial.

A generator needing a helper image is the normal case rather than an exotic one: the whole point
of ``image:`` there is that the tool is absent from the process composing the campaign.

**This file has been deleted once already, by a merge.** A pull request branched from a base that
predated the fix reverted it and took these tests with it -- so nothing was left to catch the
regression, CI stayed green, and it resurfaced as the same campaign failure a release later. Hence
:func:`test_the_call_site_still_exists`, which fails on the *shape* of the code rather than on
behaviour: behavioural tests cannot notice their own absence.
"""

import textwrap

import pytest
import yaml

from robovast.execution.cluster_execution.container_runner import required_container_specs


#: The fields the schema requires of any `.vast`, so each fixture below states only what it is
#: about. Kept as a suffix rather than repeated: a fixture that differs from the others in a way
#: the test does not name is a test that can pass for the wrong reason.
_REQUIRED = """\
  containers:
    scenario: {}
  runs: 1
"""


def _vast(tmp_path, body: str):
    """Write a fixture `.vast`, and check it is the shape it claims to be before a test trusts it.

    The body is dedented, so ``execution:`` sits at column 0 and _REQUIRED's two-space indent lands
    under it -- _REQUIRED is deliberately NOT dedented for that reason. The assertions are what make
    that safe: appended text landing at the wrong depth is otherwise silent, and a fixture that is
    not the campaign it looks like is a test that can pass for the wrong reason.
    """
    text = textwrap.dedent(body) + _REQUIRED
    parsed = yaml.safe_load(text)
    assert "generate" in parsed["execution"] or "variations" in parsed["configuration"][0], (
        "fixture declares neither a generator nor a variation, so it tests nothing"
    )
    assert "containers" in parsed["execution"] and "runs" in parsed["execution"], (
        "the required execution fields did not land under `execution:` -- check the indentation"
    )
    path = tmp_path / "campaign.vast"
    path.write_text(text, encoding="utf-8")
    return str(path)


def test_a_generator_declaring_an_image_requires_an_aux_container(tmp_path):
    """THE regression: this returned [] and the campaign died while composing."""
    config = _vast(tmp_path, """
        version: 3
        metadata:
          name: gen-needs-image
        configuration:
        - name: only
        execution:
          generate:
          - shell:
              out: derived
              image: family:robovast-roqsim
              command: some-tool --out {out}
          scenario_file: scenario.osc
    """)
    specs = required_container_specs(config)
    assert [s.image for s in specs] == ["family:robovast-roqsim"], (
        "an input generator's helper image must reach aux discovery; without it the cluster lane "
        "installs no runner factory and composition fails before any trial runs"
    )


def test_a_generator_without_an_image_requires_nothing(tmp_path):
    """The common case must not conjure a pod: a generator whose tool is beside the composer."""
    config = _vast(tmp_path, """
        version: 3
        metadata:
          name: gen-no-image
        configuration:
        - name: only
        execution:
          generate:
          - shell:
              out: derived
              command: some-tool --out {out}
          scenario_file: scenario.osc
    """)
    assert required_container_specs(config) == []


def test_a_campaign_with_neither_requires_nothing(tmp_path):
    config = _vast(tmp_path, """
        version: 3
        metadata:
          name: plain
        configuration:
        - name: only
          variations:
          - ParameterVariationList:
              scenario: speed
              values: [1.0, 2.0]
        execution:
          scenario_file: scenario.osc
    """)
    assert required_container_specs(config) == []


def test_a_variation_and_a_generator_sharing_an_image_are_deduplicated(tmp_path):
    """One pod per distinct container, whichever kind of declaration asked for it."""
    config = _vast(tmp_path, """
        version: 3
        metadata:
          name: both
        configuration:
        - name: only
          variations:
          - ParameterVariationList:
              scenario: speed
              values: [1.0]
        execution:
          generate:
          - shell:
              out: a
              image: family:robovast-roqsim
              command: t --out {out}
          - shell:
              out: b
              image: family:robovast-roqsim
              command: t --out {out}
          scenario_file: scenario.osc
    """)
    specs = required_container_specs(config)
    assert len(specs) == 1, f"expected one deduplicated spec, got {[s.image for s in specs]}"


def test_an_unknown_generator_is_not_silently_treated_as_needing_nothing(tmp_path):
    """Discovery must never fail towards "no container needed".

    Returning [] on a resolution failure is the dangerous direction: the campaign would launch
    with no aux pod and fail later, in a phase that does not name the generator.
    """
    config = _vast(tmp_path, """
        version: 3
        metadata:
          name: bogus
        configuration:
        - name: only
        execution:
          generate:
          - no_such_generator:
              out: derived
              image: family:robovast-roqsim
          scenario_file: scenario.osc
    """)
    with pytest.raises(Exception, match="no_such_generator|Unknown input generator"):
        required_container_specs(config)


def test_the_call_site_still_exists():
    """The generator branch is reachable from discovery -- checked structurally, on purpose.

    Every other test here would pass if this file were deleted, which is exactly how the fix was
    lost the first time: a stale branch reverted the source and the tests together. This asserts on
    the source text, so re-applying an old revision of ``_discover_specs`` fails here even if
    someone also drops the behavioural tests.
    """
    import inspect

    from robovast.execution.cluster_execution import container_runner

    source = inspect.getsource(container_runner._discover_specs)
    assert "_generator_container_specs" in source, (
        "_discover_specs no longer asks the input generators for their container. This was "
        "reverted once by a merge from a stale base; if that has happened again, restore the call "
        "rather than deleting this test."
    )
