# Copyright (C) 2026 Frederik Pasch
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Controller-pod bootstrap for service-launched cluster campaigns.

When the persistent ``robovast-service`` launches a campaign (mode 3), it stages
the workspace's project into the object store and starts a controller pod whose
entrypoint is this module. Here we:

1. reconstruct the cluster config from the injected env (same vars the legacy
   ``vast exec cluster run`` path injects — see
   :func:`robovast.execution.controller._build_cluster_backend`);
2. download the staged project from the object store into ``/workspace/project``;
3. ``exec`` the existing controller
   (``python -m robovast.execution.controller``) against that project.

This replaces the host's ``kubectl cp`` of inputs with an object-store pull, so
the launcher needs no ``kubectl`` in the image and no shell into the pod — the
service creates the pod with the kubernetes API and the pod is self-sufficient.

Required env (set by
:meth:`robovast.service.cluster_service.ClusterService.create_campaign`):

* ``ROBOVAST_CLUSTER_CONFIG_NAME`` / ``ROBOVAST_CLUSTER_CONFIG_KWARGS`` — cluster
  config (object store endpoint/creds), reused by the controller too.
* ``ROBOVAST_STAGING_BUCKET`` / ``ROBOVAST_STAGING_PREFIX`` — where the project
  was staged.
* ``ROBOVAST_CAMPAIGN_ID`` — the campaign id (already generated by the service).
* ``ROBOVAST_RUNS`` / ``ROBOVAST_CONFIG_FILTER`` — optional overrides.
* ``ROBOVAST_NAMESPACE`` — the pod namespace (also read by the controller).
"""

import json
import logging
import os
import sys

logger = logging.getLogger("robovast.execution.cluster_bootstrap")

WORKSPACE_DIR = "/workspace"
PROJECT_DIR = "/workspace/project"
RESULTS_DIR = "/workspace/results"


def _cluster_config_from_env():
    from robovast.execution.cluster_execution.cluster_setup import \
        get_cluster_config
    name = os.environ.get("ROBOVAST_CLUSTER_CONFIG_NAME")
    if not name:
        raise RuntimeError("ROBOVAST_CLUSTER_CONFIG_NAME is not set")
    cfg = get_cluster_config(name)
    kwargs_json = os.environ.get("ROBOVAST_CLUSTER_CONFIG_KWARGS")
    if kwargs_json:
        cfg.restore_from_setup_kwargs(json.loads(kwargs_json))
    return cfg


def _download_project(cluster_config) -> str:
    """Pull the staged project from the object store into :data:`PROJECT_DIR`."""
    from robovast.execution.cluster_execution import in_pod_storage
    bucket = os.environ["ROBOVAST_STAGING_BUCKET"]
    prefix = os.environ["ROBOVAST_STAGING_PREFIX"]
    os.makedirs(PROJECT_DIR, exist_ok=True)
    storage = in_pod_storage.storage_client_for(cluster_config)
    n = storage.download_prefix(bucket, prefix, PROJECT_DIR)
    logger.info("Downloaded %d project file(s) from %s/%s", n, bucket, prefix)
    return PROJECT_DIR


def _find_vast(project_dir: str) -> str:
    # An explicit selection (the service passes the campaign's chosen .vast) wins;
    # else auto-pick when there is exactly one, else demand a selection.
    rel = os.environ.get("ROBOVAST_CONFIG_PATH", "").strip()
    if rel:
        base = os.path.abspath(project_dir)
        chosen = os.path.abspath(os.path.join(base, rel))
        if os.path.commonpath([base, chosen]) != base or not os.path.isfile(chosen):
            raise RuntimeError(f"ROBOVAST_CONFIG_PATH {rel!r} not found under {project_dir}")
        return chosen
    vasts = sorted(
        os.path.join(dp, f)
        for dp, _dn, fns in os.walk(project_dir) for f in fns if f.endswith(".vast"))
    if not vasts:
        raise RuntimeError(f"no .vast file found under {project_dir}")
    if len(vasts) > 1:
        raise RuntimeError(
            f"multiple .vast files under {project_dir}: {vasts}; "
            "set ROBOVAST_CONFIG_PATH to choose")
    return vasts[0]


def main(argv=None) -> int:
    logging.basicConfig(
        level=os.environ.get("ROBOVAST_LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s")

    cluster_config = _cluster_config_from_env()
    project_dir = _download_project(cluster_config)
    vast_file = _find_vast(project_dir)
    os.makedirs(RESULTS_DIR, exist_ok=True)

    # Variation plugins the .vast declares in ``plugins:`` were installed into the
    # workspace's ``.robovast_plugins/`` by the service before staging, so they
    # arrived with the project download above. The controller only needs them on
    # ``sys.path`` (handled during composition by ``ensure_workspace_plugins``);
    # add the dir to PYTHONPATH here too so any child process sees it. The pod
    # never installs or clones.
    plugin_dir = os.path.join(project_dir, ".robovast_plugins")
    if os.path.isdir(plugin_dir):
        existing = os.environ.get("PYTHONPATH", "")
        os.environ["PYTHONPATH"] = plugin_dir + (os.pathsep + existing if existing else "")
        logger.info("Added workspace plugin dir to PYTHONPATH: %s", plugin_dir)

    cmd = [
        sys.executable, "-m", "robovast.execution.controller",
        "--vast", vast_file,
        "--results-dir", RESULTS_DIR,
        "--namespace", os.environ.get("ROBOVAST_NAMESPACE", "default"),
        "--campaign-id", os.environ["ROBOVAST_CAMPAIGN_ID"],
    ]
    runs = os.environ.get("ROBOVAST_RUNS")
    if runs:
        cmd += ["--runs", runs]
    config_filter = os.environ.get("ROBOVAST_CONFIG_FILTER")
    if config_filter:
        cmd += ["--config", config_filter]

    logger.info("Starting controller: %s", " ".join(cmd))
    # Replace this process with the controller so it becomes the pod's PID 1
    # payload (its /status control channel + signal handling behave as usual).
    os.execv(cmd[0], cmd)
    return 0  # unreachable


if __name__ == "__main__":
    raise SystemExit(main())
