apiVersion: batch/v1
kind: Job
metadata:
  name: $SCENARIO_ID
  labels:
    jobgroup: scenario-runs
spec:
  backoffLimit: 0
  # activeDeadlineSeconds: 10000000
  template:
    metadata:
      name: scenario-runs
      labels:
        jobgroup: scenario-runs
    spec:
      restartPolicy: Never
      privileged: true
      securityContext:
        privileged: true
      containers:
        - name: example-container
          # image: freeedlabs/scenario_execution_jazzy@sha256:53c128913bc373f93a70fe6b4c3e879c2bcd6b9129a93be8328bcd4265b038ff
          #image: ghcr.io/cps-test-lab/robovast:latest
          image: robovast_jazzy:latest
          # command: ["/bin/bash", "-c", "sleep 1000"]
          # command: ["/entrypoint.sh", "/config/common/run.sh"]
          securityContext: # required for rke2
            privileged: true
          # - name: NOVNC_ENABLE
          #   value: "true"
          resources:
            requests:
              cpu: "1"
            limits:
              cpu: "1"

      volumes:
        - name: transfer-storage
          hostPath: # for rke2
            path: "/transfer"
            type: Directory
          # nfs: # for gcp
          #   server: nfs-server.default.svc.cluster.local
          #   path: "/"
