defaults:
  - scenario: sweep
  #- override hydra/sweeper: optuna
  - override hydra/sweeper: basic
  - _self_

hydra:
  sweeper:
    #sampler:
    #  _target_: optuna.samplers.GridSampler
    #direction: maximize
    #n_trials: 2
    params:
      scenario.growth_rate: choice(0.1, 0.3)
      scenario.initial_population: choice(1)
      trial: range(3)

metadata:
  name: growth_sim

execution:
  image: ghcr.io/cps-test-lab/robovast:latest
  resources:
    cpu: 1
  env:
    - ENABLE_X11: "false"
  scenario_file: scenario.osc
  run_files:
    - "files/*.py"
    - "files/*.sh"
  pre_command: /config/files/pre_command.sh
  post_command: /config/files/post_command.sh

results_processing:
  postprocessing:
    - command:
        script: postprocess.sh

evaluation:
  visualization:
    - Analysis:
        run: analysis/analysis_run.ipynb
        config: analysis/analysis_config.ipynb
        campaign: analysis/analysis_campaign.ipynb
