defaults:
  - scenario: sweep
  - _self_

metadata:
  name: growth_sim

execution:
  image: ghcr.io/cps-test-lab/robovast:latest
  resources:
    cpu: 1
  runs: 20
  env:
    - ENABLE_X11: "false"
  scenario_file: scenario.osc
  run_files:
    - "files/*.py"
    - "files/*.sh"
  pre_command: /config/files/pre_command.sh
  post_command: /config/files/post_command.sh

results_processing:
  postprocessing:
    - command:
        script: postprocess.sh

evaluation:
  visualization:
    - Analysis:
        run: analysis/analysis_run.ipynb
        config: analysis/analysis_config.ipynb
        campaign: analysis/analysis_campaign.ipynb
